Controllers/CompraController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rest_Bar_El_Drag_n_.Models;

namespace Rest_Bar_El_Drag_n_.Controllers
{
    public class CompraController : Controller
    {
        private RestauranteContext _context;
        public CompraController(RestauranteContext c) {
            _context = c;
        }
    
        public IActionResult Index(Compra x)
        {
            var compras= _context.Compras.ToList();
           // var lista = _context.Menus.Take(15).ToList();
            return View(compras);
        }

        [HttpPost]
        public IActionResult Registro(Compra x)
        {
            if (ModelState.IsValid) {
                x.Fecha=DateTime.Now;
                _context.Add(x);
                _context.SaveChanges();
                
            }
                TempData["Success"]="ASd";
                return RedirectToAction("Index","Home", new { p = 1});
        }

    }
}

Controllers/CuentaController.cs
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rest_Bar_El_Drag_n_.Models;

namespace Rest_Bar_El_Drag_n_.Controllers
{
    public class CuentaController : Controller
    {
        private RestauranteContext _context;
        private SignInManager<IdentityUser> _sim;
        private UserManager<IdentityUser> _um;
        private RoleManager<IdentityRole> _rm;
        public CuentaController(
            RestauranteContext c,  
            SignInManager<IdentityUser> s,
            UserManager<IdentityUser> um,
            RoleManager<IdentityRole> rm) {

            _context = c;
            _sim = s;
            _um = um;
            _rm = rm;
        }

        public IActionResult AsociarRol()
        {
            ViewBag.Usuarios = _um.Users.ToList();
            ViewBag.Roles = _rm.Roles.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult AsociarRol(string usuario, string rol) {
            var user = _um.FindByIdAsync(usuario).Result;

            var resultado = _um.AddToRoleAsync(user, rol).Result;

            return RedirectToAction("index", "home");
        }

        public IActionResult CrearRol()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearRol(string nombre)
        {
            var rol = new IdentityRole();
            rol.Name = nombre;

            var resultado = _rm.CreateAsync(rol).Result;

            return RedirectToAction("index", "home");
        }

        public IActionResult Crear() {
            return View();
        }

        public IActionResult AccesoDenegado() {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(CrearCuentaViewModel model) {
            if (ModelState.IsValid) {
                // Guardar datos del modelo en la tabla usuarios
                var usuario = new IdentityUser();
                usuario.UserName = model.Correo;
                usuario.Email = model.Correo;

                IdentityResult resultado = _um.CreateAsync(usuario, model.Password1).Result;
                var r = _um.AddToRoleAsync(usuario, "Usuario").Result;


                
            if (resultado.Succeeded) {
                    return RedirectToAction("index", "home");
                }
                else {
                    foreach (var item in resultado.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }                
            }

            return View(model);
        }

        public IActionResult Login() {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model) {

            if (ModelState.IsValid) {

             
                var resultado = _sim.PasswordSignInAsync(model.Correo, model.Password, true, false).Result;

                if (resultado.Succeeded) {

                    return RedirectToAction("index", "home");
                }
                else {
                    
                    ModelState.AddModelError("", "Datos incorrectos");
                }
            }        

            return View(model);
        }

        public IActionResult Logout() {
            _sim.SignOutAsync();

            return RedirectToAction("index", "home");
        }
    }
}

Controllers/MenuController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rest_Bar_El_Drag_n_.Models;

namespace Rest_Bar_El_Drag_n_.Controllers
{
    public class MenuController : Controller
    {
        private RestauranteContext _context;
        public MenuController(RestauranteContext c) {
            _context = c;
        }
        public IActionResult Index()
        {
            var categorias= _context.Categorias.Include(x => x.Menus).ToList();
           // var lista = _context.Menus.Take(15).ToList();
            return View(categorias);
        }
        public IActionResult Registro()
        {
            ViewBag.Categorias = _context.Categorias.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Registro(Menu x)
        {
            if (ModelState.IsValid) {
                _context.Add(x);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Categorias = _context.Categorias.ToList();
            return View(x);
        }
    }
}

Controllers/ReservaController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rest_Bar_El_Drag_n_.Models;

namespace Rest_Bar_El_Drag_n_.Controllers
{
    public class ReservaController : Controller
    {
         private RestauranteContext _context;
        public ReservaController(RestauranteContext c) {
            _context = c;
        }
        [Authorize(Roles="Administrador")]
        public IActionResult Index()
        {
            var lista = _context.Reservas.ToList();
            return View(lista);
        }
        public IActionResult Registro()
        {
            
            return View();
        }
        public IActionResult Ocupado()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Registro(Reserva x)
        {
            var lista = _context.Reservas.ToList();
            Boolean estado =false;
            if (ModelState.IsValid) {
                for (int i =0; i <lista.Count() ; i++)
                {
                    if(x.FechayHora == lista[i].FechayHora || x.NumerodeMesa == lista[i].NumerodeMesa){
                        estado =true;
                    }
                }
                if(!estado){
                    _context.Add(x);
                    _context.SaveChanges();
                
                }else{
                    return RedirectToAction("Ocupado");
                }
                
            }
            return RedirectToAction("Index","Home", new { p = 2});
            
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rest_Bar_El_Drag_n_</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>            
        <nav class="barra">
            <img class="img1" src="https://scontent.flim1-1.fna.fbcdn.net/v/t31.0-8/p960x960/17917249_440078649670828_2953024631432677971_o.png?_nc_cat=100&_nc_oc=AQnoFT0vNtMIJDpjUeuYoWi_iRvh6YLn8sIBnmWKGW2tSLmVLb_4hJ4hqsx-U0OkNUE&_nc_ht=scontent.flim1-1.fna&oh=664b8f8407d7d9d59dc8eef287f056cd&oe=5E4F0110" alt="">
            <ul class="bar1">
                <li class="li1">
                    <a asp-controller="Home" asp-action="Index">Inicio</a>
                </li>
                <li class="li1">
                        <a asp-controller="Home" asp-action="Nosotros">Nosotros</a>
                    </li>
                    <li class="li1">
                            <a asp-controller="Menu" asp-action="Index">Menu</a>
                    </li>
                     @if (!User.Identity.IsAuthenticated) {
                    <li class="li1">
                        <a asp-controller="Cuenta" asp-action="Crear"> Crear cuenta</a>
                    </li>
                     <li class="li1">
                        <a asp-controller="Cuenta" asp-action="Login"> Iniciar sesión</a>
                    </li>
                     }else{

                    <li class="li1">
                        <a asp-controller="Reserva" asp-action="Registro"> Registrar Reserva</a>
                    </li>
                    
                    

                     <li class="li1">
                        <a asp-controller="Cuenta" asp-action="Logout"> Cerrar sesión</a>
                    </li>
                    }
                    
                    


                        

            </ul>
            @if (User.Identity.IsAuthenticated) {  
             var usuario= UserManager.FindByNameAsync(User.Identity.Name).Result;
                    @if(UserManager.IsInRoleAsync(usuario,"Administrador").Result){
                        
            <div class="dropdown">
                            <button class="dropbtn">Opciones de Administrador</button>
                                <div class="dropdown-content">
                                    <a asp-controller="Menu" asp-action="Registro"> Registrar Plato</a>
                                    <a asp-controller="Categorias" asp-action="Registro"> Registrar Categoria</a>
                                    <a asp-controller="Compra" asp-action="Index"> Ver Compras</a>
                                    <a asp-controller="Reserva" asp-action="Index"> Ver Reservas</a>
                                    <a  href="~/cuenta/crearrol">Crear Rol</a>
                                    <a  href="~/cuenta/asociarrol">Asociar Rol</a>
                                </div>
                        </div>  
                    } 
                     }
        </nav>
    </header>
    @RenderBody()

    <footer class="footer">
        <div class="container">
            reservas@eldragon.com Camino Real 101
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>